name: "Gump"
mode: "dev"
port: 3000
version: "v.0.0.1"
start_time: "2021-12-28"
machine_id: 1

log:
  level: "debug"
  file_name: "Gump.log"
  max_size: 200
  max_age: 10
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "Gump"
  mysql_max_open_conns: 200
  mysql_max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port:
  db: 0
  password: ""
  pool_size: 100
